### ISSUE TITLE
Custom Trained Model for Object Detection

### ISSUE THREAD

**Issue by aliBUT** [Syn-McJ/TFClassify-Unity#13]
So Classify is working fine. I decided to try out object detection. Everything works fine as long as I use your model so I trained my modal by following [this ](https://blogs.msdn.microsoft.com/esmsdn/2018/04/09/post-invitado-part2-step-by-step-how-to-training-your-own-detector-classifier/) tutorial

I am facing the same issue as my trained modal doesn't work. I made sure input is image tensor and use SS mobile net v2 lite for training. I am not sure what is the issue here

this is my model and label map

https://www.dropbox.com/s/sgtolycu2t0hx7b/graph.zip?dl=0

Any help will be appreciated

**Comment by aliBUT** [comment]
did you manage to find out whats wrong in my model?

**Comment by aliBUT** [comment]
so I trained a new model with different image size and tried it with the same result, I don't see input and out names here or am I missing anything?

**Comment by Syn-McJ** [comment]
Hi, @aliBUT. Sorry, but I haven't had time to look at your model yet. If you are in hurry, I suggest first to make sure your model works with [TensorFlow Android example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android). If it does work there but doesn't work here, then it's a problem with my example. Otherwise, it's a problem with how you train your model and maybe you'll solve it faster by going through documentation or opening issue in there.

I'll try to check your model this week.

**Comment by iiidefektiii** [comment]
@Syn-McJ Is the retrain process different for classify then it is for detect? Can the same retrained graph not work for both? Just curious because now that I have the classify version working correctly with my own images it does not work for the detect version using the same graph and labels.

**Comment by Syn-McJ** [comment]
@iiidefektiii yes, retrain process for classify and detect is different since detection model actually does much more work with estimating object boundaries, etc. If you want to train your own detection model I suggest you to [start here](https://github.com/tensorflow/models/tree/master/research/object_detection/).

**Comment by iiidefektiii** [comment]
Just landed on that page after typing that out didn't know there was a difference until I saw this thread and tried the classify graph. 

EDIT
Are there any specific version I should be aware of for this one as well?

**Comment by Syn-McJ** [comment]
@iiidefektiii same as with classify, you can either use tensorflow 1.4 with 0.3 plugin or tensorflow 1.7.1 with 0.4 plugin.

@aliBUT I checked your model and it kinda works. It's just slow and not very accurate:
![screenshot_20180815-211458_tf classify unity - copy](https://user-images.githubusercontent.com/7733989/44153052-52343100-a0d1-11e8-8b93-e83438aa5d5e.jpg)

As I mentioned in the readme, performance of both samples (especially detection) is far from great right now and I'm not sure how to improve that, so I'm afraid you are on your own if you really need a well working detection in Unity.

**Comment by aliBUT** [comment]
hi, @Syn-McJ I just realized we need to add "???" on top of our label map to make it work.I am not sure why but my model is working now.

**Comment by Syn-McJ** [comment]
@aliBUT glad it's figured out. I'm gonna close this issue if that's the case.
