### ISSUE TITLE
TFException: Expects arg[0] to be uint8 but float is provided

### ISSUE THREAD

**Issue by hanselkoh** [Syn-McJ/TFClassify-Unity#37]
I am facing the above exception when using my trained model. I did used Tensorflow 1.4 with Python 3.6.10 for the training, and did managed to test the model in pycharm. 

So I wonder if anyone is facing the same issue?

**Comment by Syn-McJ** [comment]
Not sure what's wrong here, but if you provide a model that's causing such error, I could look into it.

**Comment by hanselkoh** [comment]
@Syn-McJ Thank you for responding! 

The model file the I trained
https://drive.google.com/open?id=153MvrA15xJzHV1eWehBB0aaKAmUf-0hS

INPUT_TENSOR = "DecodeJpeg";
OUTPUT_TENSOR = "final_result";

I trained the model using the following steps on the link below.
https://github.com/MicrocontrollersAndMore/TensorFlow_Tut_2_Classification_Walk-through

I am guessing it was the way the model was trained, but searching around always led me to the similar configuration on the training.

**Comment by Syn-McJ** [comment]
@hanselkoh 
Your model (Inception_v3 I take it) has DecodeJpeg operation that is not supported on mobile. In fact, Inception starts with a bunch of layers that pre-process an image into an array of pixels and apply scale/bias to pixel values to make them fall within a certain range. But in my example pre-processing is manual (because of unsupported ops), so the model has to be stripped of all those layers. 

CoreML has a good example of how to do that: https://github.com/apple/coremltools/blob/master/examples/neural_network_inference/tensorflow_converter/Tensorflow_1/inception_v3.ipynb
The cells that start with "# Load the TF graph definition" and then "# Strip the JPEG decoder" is what you need, except in your case `output_node_names` will be "final_result".

However, after I tried to do that and run the stripped model in Unity, I got an error indicating TF versions mismatch. What TensorFlow version did you use for training?

**Comment by hanselkoh** [comment]
Ah.. I didn't know DecodeJpeg wasn't supported on mobile.

Thanks for providing the example, but I am new to this area, so I will take me sometime to figure out the process of stripping those layers.

I did used TensorFlow 1.4 to train my model, I guess is the right version

**Comment by Syn-McJ** [comment]
@hanselkoh 
The process of stripping layers is very simple, you just need to run the code from those two cells that I indicated, but don't forget to replace names of files and output to yours.

I think in my case the problem is that I've run stripping using tf 1.14, I'll try with 1.4 later.

**Comment by Syn-McJ** [comment]
Just a heads up - if you train MobileNet model instead of Inception, you will avoid DecodeJpeg problem and also can try my [new example](https://github.com/Syn-McJ/TFClassify-Unity-Barracuda) with Unity Barracuda which doesn't care about TensorFlow version.

Pretty sure you can do that just by uncommenting architecture line in retrain.py that you used like this:
ARCHITECTURE = 'mobilenet_1.0_224'
\# ARCHITECTURE = 'inception_v3'

**Comment by Syn-McJ** [comment]
Stripping layers with tf1.4 seemed to work - here is the file:
https://drive.google.com/open?id=1v5-ksbEQpwcVHlRrGDxOy7DTIsoFkXnu

Parameters:

public const int IMAGE_SIZE = 299;
private const int IMAGE_MEAN = 128;
private const float IMAGE_STD = 128f;
private const string INPUT_NAME = "Mul";
private const string OUTPUT_NAME = "final_result";

// in phonecamera.cs
private const int classifyImageSize = 299;

But performance isn't good with this one. Once again, I recommend to train MobileNet - it's an architecture specifically designed for mobile devices.

**Comment by hanselkoh** [comment]
Thank you for taking the time to help. Appreciated it.

I will give it a shot to strip the model, then move on the mobile net. Thank you!

**Comment by Syn-McJ** [comment]
I assume you've resolved the problem. Feel free to reopen if needed.
